#!/bin/bash

sudo cp /etc/bind/named.conf.forwarders /etc/bind/named.conf.forwarders-jvpn
sudo cp /usr/local/var/lib/jvpn/forward /etc/bind/named.conf.forwarders

sudo service bind9 reload

cat <<'EOF' > /tmp/resol.txt
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
search local

EOF

sudo cp /tmp/resol.txt /etc/resolv.conf

