#!/bin/bash
BIND_IP=127.0.0.1
 
NAMED_FORWARDERS=/etc/bind/named.conf.forwarders
NAMED_INITD=/etc/init.d/bind9
RESOLV_CONF=/etc/resolv.conf
 
echo $new_domain_name_servers | sed -e '
iforwarders {\n
s/\([^ ]\+\)\s*/ \1;\n/g
a};' > "$NAMED_FORWARDERS"
 
"$NAMED_INITD" restart
 
# sed -e "
# \$anameserver $BIND_IP
# /^\s*nameserver/i# moved following nameserver to bind forwarders
# s/^\s*nameserver/# nameserver/" -i "$RESOLV_CONF"
