#!/bin/sh

MACCHANGER=/usr/bin/macchanger

test -x $ETHTOOL || exit 0

[ "$IFACE" != "lo" ] || exit 0

# Bring down interface (for wireless cards that are up to scan for networks), change MAC address to a random vendor address, bring up the interface
[ "$IFACE" != "eth0" ] || ifconfig "$IFACE" down
macchanger -A "$IFACE"
[ "$IFACE" != "eth0" ] || ifconfig "$IFACE" up
exit 0


